// [SCOPE] Analyzer report generators — project map markdown, recommendations markdown, and per-file analysis
import * as path from 'path';
import { AnalysisResult } from './analyzerTypes.js';

// [SCOPE] Generate project_map.md markdown from analysis result
export function generateProjectMap(result: AnalysisResult, root: string): string {
  const projectName = path.basename(root);
  let md = `# Project Map — ${projectName}\n\n`;
  md += `*Generated by CHASSIS Analyzer*\n\n---\n\n`;
  md += `## Overview\n\n`;
  md += `| Metric | Count |\n|--------|-------|\n`;
  md += `| Total Files | ${result.totalFiles} |\n`;
  md += `| Total Lines | ${result.totalLines.toLocaleString()} |\n`;
  md += `| Large Files (>200 lines) | ${result.largeFiles.length} |\n`;
  md += `| TODO/FIXME items | ${result.todoItems.length} |\n`;
  md += `| Files without comments | ${result.uncommentedFiles.length} |\n`;
  md += `| Files missing [SCOPE] at line 1 | ${result.missingScopeFiles?.length || 0} |\n\n`;

  md += `## File Types\n\n`;
  const sorted = Object.entries(result.filesByType).sort((a, b) => b[1] - a[1]);
  for (const [ext, count] of sorted) { md += `- **${ext}**: ${count} files\n`; }
  md += `\n`;

  md += `## Directory Structure\n\n`;
  md += '```\n';
  for (const dir of result.structure) {
    const depth = dir.split(path.sep).length - 1;
    md += `${'  '.repeat(depth)}📁 ${dir}\n`;
  }
  md += '```\n\n';

  if (result.largeFiles.length > 0) {
    md += `## ⚠️ Large Files (>200 lines)\n\n`;
    md += `These should be reviewed for splitting:\n\n`;
    for (const f of result.largeFiles) { md += `- **${f.relativePath}** — ${f.lines} lines\n`; }
    md += `\n`;
  }
  if (result.todoItems.length > 0) {
    md += `## 📋 Existing TODOs & FIXMEs\n\n`;
    md += `Convert these to CHASSIS annotations (\`// [TODO]\`, \`// [DONE]\`, etc.):\n\n`;
    for (const t of result.todoItems) { md += `- **${t.file}** — ${t.line}\n`; }
    md += `\n`;
  }
  if (result.uncommentedFiles.length > 0) {
    md += `## 🔇 Files Without Comments\n\n`;
    md += `Consider adding \`// [SCOPE]\` tags to define boundaries:\n\n`;
    for (const f of result.uncommentedFiles) { md += `- **${f.relativePath}** (${f.lines} lines)\n`; }
    md += `\n`;
  }
  if (result.missingScopeFiles && result.missingScopeFiles.length > 0) {
    md += `## ❌ Files Missing [SCOPE] at Line 1\n\n`;
    md += `These code files lack the mandatory CHASSIS scope tag at their very first line:\n\n`;
    for (const f of result.missingScopeFiles) { md += `- **${f.relativePath}**\n`; }
    md += `\n`;
  }
  return md;
}

// [SCOPE] Generate recommendations.md markdown from analysis result
export function generateRecommendations(result: AnalysisResult): string {
  let md = `# CHASSIS Recommendations\n\n`;
  md += `*Based on project analysis*\n\n---\n\n`;
  md += `## Priority Actions\n\n`;
  let priority = 1;

  if (result.largeFiles.length > 0) {
    md += `### ${priority++}. Split Large Files\n\n`;
    md += `${result.largeFiles.length} files exceed 200 lines. `;
    md += `Large files are harder for AI coders to hold in context and more prone to merge conflicts.\n\n`;
    for (const f of result.largeFiles.slice(0, 5)) {
      md += `- \`${f.relativePath}\` (${f.lines} lines) — consider splitting by function/responsibility\n`;
    }
    md += `\n`;
  }
  if (result.todoItems.length > 0) {
    md += `### ${priority++}. Convert TODOs to CHASSIS Annotations\n\n`;
    md += `Found ${result.todoItems.length} existing TODO/FIXME markers. Convert them:\n\n`;
    md += `| Old Style | CHASSIS Style |\n|-----------|---------------|\n`;
    md += `| \`// TODO\` | \`// [TODO] description\` |\n`;
    md += `| \`// FIXME\` | \`// [WARN] description\` |\n`;
    md += `| \`// HACK\` | \`// [WARN] hacky — description\` |\n`;
    md += `| \`// XXX\` | \`// [TODO] needs attention — description\` |\n\n`;
  }
  if (result.uncommentedFiles.length > 0) {
    md += `### ${priority++}. Add Scope Tags\n\n`;
    md += `${result.uncommentedFiles.length} code files have zero comments. `;
    md += `Add a \`// [SCOPE]\` tag at the top of each file describing its purpose:\n\n`;
    md += `\`\`\`\n// [SCOPE] WebSocket bridge — connects TUI dashboard to browser avatar\n\`\`\`\n\n`;
  }
  md += `### ${priority++}. Add Entry Point Comments\n\n`;
  md += `Every main file should have a \`// [SCOPE]\` tag explaining what it does and what it connects to. `;
  md += `This is the single most valuable annotation for cold-read handoff.\n\n`;
  md += `### ${priority++}. Establish File Size Discipline\n\n`;
  md += `Going forward, aim for **200 lines max per file**. `;
  md += `When a file exceeds this, split it by responsibility. `;
  md += `CHASSIS will flag violations automatically in future versions.\n\n`;
  md += `---\n\n`;
  md += `*These recommendations are structural. Deep code analysis requires CHASSIS Phase 2 (AI routing).*\n`;
  return md;
}

// [SCOPE] Analyze a single file and return a markdown report of its current CHASSIS state
export async function analyzeCurrentFile(filePath: string, fileContent: string): Promise<string> {
  const lines = fileContent.split('\n');
  const ext = filePath.split('.').pop()?.toLowerCase() || '';
  const commentChar = ['py','sh','bash','yaml','yml','rb'].includes(ext) ? '#' : '//';
  let report = '# File Analysis — ' + filePath + '\n\n';
  report += '*Generated by CHASSIS Analyzer*\n\n---\n\n';
  report += '## Current State\n\n';
  report += '- **Lines:** ' + lines.length + '\n';
  report += '- **Type:** ' + (ext || 'unknown') + '\n';
  report += '- **Comment style:** ' + commentChar + '\n';

  const tags = ['[SCOPE]', '[TODO]', '[NEXT]', '[WARN]', '[DEAD]', '[DONE]'];
  const found: string[] = [];
  for (const tag of tags) {
    const escaped = tag.replace(/[\[\]]/g, '\\$&');
    const count = (fileContent.match(new RegExp(escaped, 'g')) || []).length;
    if (count > 0) { found.push(tag + ' x' + count); }
  }
  report += '- **CHASSIS tags:** ' + (found.length > 0 ? found.join(', ') : 'None') + '\n';

  const oldTodos: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (/\b(TODO|FIXME|HACK|XXX|BUG)\b/i.test(lines[i]) && !/\[(TODO|WARN|NEXT|DEAD|DONE|SCOPE)\]/i.test(lines[i])) {
      oldTodos.push('  L' + (i + 1) + ': ' + lines[i].trim().substring(0, 80));
    }
  }
  report += '- **Old-style TODOs:** ' + oldTodos.length + '\n';

  const commentLines = lines.filter(l => {
    const t = l.trim();
    return t.startsWith('#') || t.startsWith('//') || t.startsWith('/*') || t.startsWith('<!--');
  }).length;
  const commentRatio = Math.round((commentLines / lines.length) * 100);
  report += '- **Comment density:** ' + commentRatio + '% (' + commentLines + ' lines)\n';

  const functions = lines.filter(l => /^\s*(def |function |class |export |const \w+ = \(|async function)/.test(l));
  report += '- **Functions/classes:** ' + functions.length + '\n\n';

  if (oldTodos.length > 0) {
    report += '### Existing TODOs/FIXMEs\n\n';
    for (const t of oldTodos) { report += t + '\n'; }
    report += '\n';
  }

  report += '---\n\n## Planned CHASSIS Changes\n\n';
  const planned: string[] = [];
  if (!found.some(f => f.startsWith('[SCOPE]'))) { planned.push('Add ' + commentChar + ' [SCOPE] at top'); }
  if (oldTodos.length > 0) { planned.push('Convert ' + oldTodos.length + ' TODO/FIXME items to CHASSIS format'); }
  if (commentRatio < 5) { planned.push('Add ' + commentChar + ' [WARN] to fragile sections'); }
  if (lines.length > 500) {
    planned.push('File is ' + lines.length + ' lines — will chunk into ' + Math.ceil(lines.length / 200) + ' parts');
    planned.push('Recommend splitting into smaller files');
  }
  if (lines.length > 200) { planned.push('Add ' + commentChar + ' [NEXT] split point markers'); }
  if (planned.length === 0) { planned.push('File already meets CHASSIS standards'); }
  for (const p of planned) { report += '- ' + p + '\n'; }
  report += '\n---\n\nRun **Restructure File** or **Retrofit Project** to apply.\n';
  return report;
}
