// [SCOPE] Redivivus rules generation — builds rules.md content and writes it to all AI editor shims
// Called by redivivusInit. No config or logging logic here.

import * as fs from 'fs';
import * as path from 'path';
import type { Blueprint } from '../types/index.js';
import type { RedivivusPaths } from '../features/project/application/redivivusPaths.js';
import { writeEnabledShims } from './editorRuleFiles.js';

export function generateRules(paths: RedivivusPaths, projectName: string, blueprint: Blueprint, targetPath?: string): void {
  const root = targetPath || paths.getWorkspaceRoot();
  if (!root) {return;}

  // Canonical rules — always written. Redivivus reads these directly; they are the source of truth.
  const rulesPath = path.join(root, '.redivivus', 'rules.md');
  const rules = buildRulesContent(projectName, blueprint);
  fs.writeFileSync(rulesPath, rules);

  // AI-editor shims (CLAUDE.md, .cursorrules, etc.) are OFF by default — only the editors the user
  // opted into (redivivus.editorRuleFiles) are written, so we don't litter projects with files for
  // editors they don't use. Configure via "Redivivus: Configure Editor Rule Files".
  writeEnabledShims(root, rules, projectName);
}

function buildRulesContent(projectName: string, blueprint: Blueprint): string {
  return `# Redivivus Project Rules — ${projectName}
> Auto-generated by Redivivus. Read this file BEFORE making any changes.
> These rules apply to ALL AI editors: Windsurf, Cursor, Claude Code, Copilot, Gemini, and any other tool.
> Redivivus does not need to be installed for these rules to apply. They are self-contained.

---

## Project Blueprint
- **WHO:** ${blueprint.who || '(not set)'}
- **WHAT:** ${blueprint.what || '(not set)'}
- **WHERE:** ${blueprint.where || '(not set)'}
- **WHEN:** ${blueprint.when || '(not set)'}
- **WHY:** ${blueprint.why || '(not set)'}

---

## MANDATORY — Documentation Protocol
**NO EXCEPTIONS. This applies to every change — code, comments, config, a single line edit, anything.**

### BEFORE touching any file:
1. Read \`REDIVIVUS_ROADMAP.md\` in full.

### AFTER EVERY change — no matter how small:
2. Open \`REDIVIVUS_ROADMAP.md\` and add an entry under "Recent Fixes":
   - Which file was changed and exactly what was changed
   - Why the change was made
   - Any risk introduced
3. Update the \`*Last updated:*\` line at the bottom with today's date and what you did.

### This means:
- Fixed a typo in a comment? Update the roadmap.
- Changed a variable name? Update the roadmap.
- Added a single log line? Update the roadmap.
- **There is no change too small to skip this step.**

> If Redivivus is installed: "Done for Now" writes this automatically.
> If Redivivus is NOT installed: update \`REDIVIVUS_ROADMAP.md\` manually before you stop.
> **Failure to do this breaks the project history chain for every future AI and human working on this project.**

---

## Annotation Tags
Use these in code comments. Wrong comment style = broken build (see Rule 7).
- \`[SCOPE]\` — what this file/section does. Required at top of every file.
- \`[TODO]\` — work to be done
- \`[WARN]\` — fragile or risky code. Read before touching.
- \`[NEXT]\` — where to pick up next session
- \`[DEAD]\` — tried and failed. Don't repeat it.
- \`[DONE]\` — completed. Leave for audit trail.

---

## Rules

### Rule 1: Never Remove Annotations
Annotation tags are the project's navigation system. NEVER delete, move, or modify them without reason.

### Rule 2: Read [SCOPE] Before Modifying Any File
Every file starts with [SCOPE]. Read it. If your change doesn't fit, you're in the wrong file.

### Rule 3: Read [WARN] Before Touching Flagged Code
[WARN] marks fragile code. Understand WHY before changing anything nearby.

### Rule 4: Follow [NEXT] Tags
[NEXT] tags tell you what should happen next. Follow them in order.

### Rule 5: Don't Repeat Dead Ends
[DEAD] documents what was tried and failed. Read before proposing solutions.

### Rule 6: Update Tags When You Make Changes
- Finished a [TODO]? Change to [DONE] with what you did.
- Found something fragile? Add [WARN].
- Leaving work incomplete? Add [NEXT].
- Tried something that failed? Add [DEAD].

### Rule 7: Correct Comment Syntax Per Language
ALWAYS use the correct comment character. NEVER use // in Python. NEVER use # in JavaScript.
  Python/Shell/YAML/Ruby:       # [TAG] description
  JavaScript/TypeScript/Go/etc: // [TAG] description
  HTML/XML:                     <!-- [TAG] description -->
  CSS/SCSS:                     /* [TAG] description */
  SQL/Lua:                      -- [TAG] description

### Rule 8: Don't Remove Code Without [DEAD] Logging
If you remove or replace a block, add [DEAD] explaining what was there and why.

### Rule 9: Keep Files Under 200 Lines
Files over 200 lines should be split. Add [NEXT] at natural split points.

### Rule 10: Check .redivivus/ For Context
Before starting: read \`.redivivus/blueprint.md\`, \`.redivivus/work_log.md\`, \`REDIVIVUS_ROADMAP.md\`.

### Rule 11: Annotate All New Code
New file → [SCOPE] at top. New function → comment above it. Risky logic → [WARN]. Incomplete → [TODO] or [NEXT].

### Rule 12: No Orphan Code
Every new file needs [SCOPE]. Every feature must trace to the blueprint. If outside blueprint, add:
  [SCOPE] WARNING — Not in original blueprint. Added because: [reason]

---

### Rule 13: NO FLAT FILES
Every file lives in a folder that matches its responsibility — UI in UI, logic in logic, and so on. This applies to projects Redivivus builds and to Redivivus itself. No exceptions, no matter what vibe editor is being used.


*These rules are enforced by Redivivus. Removing this file does not remove the rules — they are in .redivivus/rules.md and every other AI editor config file in this project.*
`;
}
