// [SCOPE] Blueprint writer — writeBlueprintMd function for writing blueprint.md file
// Called by blueprintService. No interview or health calculation logic here.

import * as fs from 'fs';
import type { Blueprint } from '../../types/index.js';

export function writeBlueprintMd(bp: Blueprint, blueprintPath: string, projectName: string): void {
  const status = bp.locked ? '🔒 LOCKED' : '🔶 DRAFT';
  const content = `# Blueprint — ${projectName}

**Status:** ${status}
${bp.lockedAt ? `**Locked at:** ${bp.lockedAt}` : ''}

---

## WHO
${bp.who || '❓ Not answered'}

## WHAT
${bp.what || '❓ Not answered'}

## WHERE
${bp.where || '❓ Not answered'}

## WHEN
${bp.when || '❓ Not answered'}

## WHY
${bp.why || '❓ Not answered'}
${bp.mechanics ? `
## MECHANICS
<!-- Behavioral contract (HEAD). What the project SHOULD do, observable only. The fix-Supervisor diffs this
     against the code to diagnose issues. See REDIVIVUS_LIVING_BLUEPRINT.md. -->
${bp.mechanics}
` : ''}
---

## Health
- ✅ Confirmed: ${bp.health.confirmed}
- 🔶 Assumed: ${bp.health.assumed}
- ❓ Unknown: ${bp.health.unknown}
- **Confidence:** ${bp.health.confidence.toUpperCase()}

---

*Generated by Redivivus v${bp.version}*
`;
  // [WARN] Direct file system write, potential for path/permission errors.
  fs.writeFileSync(blueprintPath, content);
}

// [SCOPE] Syncs the internal .redivivus/blueprint.md with the current config blueprint
// Call this everywhere saveConfig is called with updated blueprint data
export function syncBlueprintMd(redivivus: any, config: any): void {
  if (!config || !config.blueprint || !redivivus.blueprintPath) {return;}
  writeBlueprintMd(config.blueprint, redivivus.blueprintPath, config.projectName || 'Unknown');
}
