// [SCOPE] Expanded 5W Interview Question Bank — data only
// Extracted from expandedInterview.ts
// [WARN] Template/data file — contains large question array literal

import { InterviewQuestion } from './expandedInterview.js';

export const EXPANDED_QUESTIONS: InterviewQuestion[] = [
  // === WHO ===
  {
    id: 'who-skill',
    category: 'who',
    question: 'What is the technical skill level of your users?',
    subtext: 'This affects UI complexity, feature exposure, and documentation needs.',
    placeholder: 'e.g., Developers, Intermediate, Beginners, Mixed',
    type: 'choice',
    choices: ['Technical/Developers', 'Intermediate (some tech knowledge)', 'Beginners (minimal tech knowledge)', 'Mixed audience'],
    required: true,
    complexityTrigger: 'standard',
  },
  {
    id: 'who-count',
    category: 'who',
    question: 'How many concurrent users do you expect?',
    subtext: 'This determines architecture choices (single-user vs. multiplayer vs. mass-scale).',
    placeholder: 'e.g., Just me, 10, 1000, 100000+',
    type: 'choice',
    choices: ['Just me (personal use)', 'Small team (2-10)', 'Medium scale (10-1000)', 'Large scale (1000-100000)', 'Mass scale (100000+)'],
    required: true,
    complexityTrigger: 'deep',
  },
  {
    id: 'who-type',
    category: 'who',
    question: 'Are these internal users or public customers?',
    subtext: 'Internal tools can skip polish; customer-facing needs more UX.',
    placeholder: 'Select user type',
    type: 'choice',
    choices: ['Internal team only', 'External customers/clients', 'Both internal and external', 'Not sure yet'],
    required: true,
    complexityTrigger: 'standard',
  },
  {
    id: 'who-accessibility',
    category: 'who',
    question: 'Any accessibility requirements?',
    subtext: 'Legal compliance and inclusivity considerations.',
    placeholder: 'Select all that apply',
    type: 'multichoice',
    choices: ['Screen reader support', 'Keyboard-only navigation', 'Mobile/touch only', 'High contrast', 'None required'],
    required: false,
    complexityTrigger: 'deep',
  },

  // === WHAT ===
  {
    id: 'what-core',
    category: 'what',
    question: 'In ONE sentence, what is the core function?',
    subtext: 'The elevator pitch. If you cannot state this simply, the scope is unclear.',
    placeholder: 'e.g., A multiplayer guessing game where players draw and guess words',
    type: 'text',
    required: true,
    complexityTrigger: 'standard',
  },
  {
    id: 'what-features',
    category: 'what',
    question: 'List the 3-5 most important features',
    subtext: 'What MUST exist for this to be considered "working"?',
    placeholder: 'e.g., Real-time drawing, Chat, Score tracking, Room creation',
    type: 'text',
    required: true,
    complexityTrigger: 'standard',
  },
  {
    id: 'what-outofscope',
    category: 'what',
    question: 'What is explicitly NOT included?',
    subtext: 'Critical for preventing scope creep. Define boundaries.',
    placeholder: 'e.g., No user accounts, No payment processing, No mobile app',
    type: 'text',
    required: false,
    complexityTrigger: 'deep',
  },
  {
    id: 'what-success',
    category: 'what',
    question: 'How will you know this is "done"?',
    subtext: 'Specific, testable success criteria.',
    placeholder: 'e.g., Users can create rooms, draw, guess, and scores update in real-time',
    type: 'text',
    required: true,
    complexityTrigger: 'deep',
  },

  // === WHERE ===
  {
    id: 'where-platform',
    category: 'where',
    question: 'What platform(s)?',
    subtext: 'Web, mobile, desktop — each has different technical requirements.',
    placeholder: 'Select platform',
    type: 'choice',
    choices: ['Web browser', 'Mobile app (iOS/Android)', 'Desktop app (Windows/Mac)', 'Multiple platforms', 'Backend/API only'],
    required: true,
    complexityTrigger: 'standard',
  },
  {
    id: 'where-deployment',
    category: 'where',
    question: 'Where will this be deployed/hosted?',
    subtext: 'Infrastructure choices affect the build.',
    placeholder: 'e.g., Vercel, AWS, Self-hosted, Not sure',
    type: 'choice',
    choices: ['Vercel/Netlify (serverless)', 'AWS/GCP/Azure (cloud)', 'Self-hosted server', 'Static hosting only', 'Not sure yet'],
    required: true,
    complexityTrigger: 'deep',
  },
  {
    id: 'where-integrations',
    category: 'where',
    question: 'Required third-party integrations?',
    subtext: 'Auth, payments, APIs, databases — each adds complexity.',
    placeholder: 'e.g., Google Auth, Stripe, Firebase, OpenAI API',
    type: 'text',
    required: false,
    complexityTrigger: 'deep',
  },
  {
    id: 'where-offline',
    category: 'where',
    question: 'Does it need to work offline?',
    subtext: 'Offline-first requires local storage, sync logic, conflict resolution.',
    placeholder: 'Yes/No',
    type: 'choice',
    choices: ['Yes — full offline support', 'Partial — cache recent data', 'No — always online'],
    required: true,
    complexityTrigger: 'deep',
  },

  // === WHEN ===
  {
    id: 'when-timeline',
    category: 'when',
    question: 'Overall timeline?',
    subtext: 'This affects how much we can polish vs. how lean we build.',
    placeholder: 'Select timeline',
    type: 'choice',
    choices: ['Today (single session)', 'This week', 'This month', 'This quarter', '6+ months'],
    required: true,
    complexityTrigger: 'standard',
  },
  {
    id: 'when-mvp',
    category: 'when',
    question: 'When do you need the MVP (minimum viable product)?',
    subtext: 'What is the absolute soonest this must be demo-able?',
    placeholder: 'e.g., End of this week',
    type: 'text',
    required: true,
    complexityTrigger: 'deep',
  },
  {
    id: 'when-realtime',
    category: 'when',
    question: 'Any real-time or performance requirements?',
    subtext: 'Real-time multiplayer, live updates, high-frequency data.',
    placeholder: 'Select all that apply',
    type: 'multichoice',
    choices: ['Real-time multiplayer/collaboration', 'Live data updates (< 1 second)', 'High-frequency processing', 'Background/async processing OK', 'No special timing needs'],
    required: false,
    complexityTrigger: 'deep',
  },

  // === WHY ===
  {
    id: 'why-problem',
    category: 'why',
    question: 'What specific problem does this solve?',
    subtext: 'The "why" — if the answer is weak, reconsider building this.',
    placeholder: 'e.g., Current tools are too expensive, too slow, or missing X feature',
    type: 'text',
    required: true,
    complexityTrigger: 'standard',
  },
  {
    id: 'why-current',
    category: 'why',
    question: 'What do you use now to solve this?',
    subtext: 'Understanding current workflow reveals integration points.',
    placeholder: 'e.g., Excel spreadsheets, multiple apps, manual process',
    type: 'text',
    required: false,
    complexityTrigger: 'deep',
  },
  {
    id: 'why-different',
    category: 'why',
    question: 'Why is this better than existing solutions?',
    subtext: 'Your differentiator — the reason this should exist.',
    placeholder: 'e.g., 10x faster, 10x cheaper, privacy-focused, simpler UX',
    type: 'text',
    required: true,
    complexityTrigger: 'deep',
  },
  {
    id: 'why-metrics',
    category: 'why',
    question: 'How will you measure success?',
    subtext: 'Quantifiable metrics prevent "feels done" ambiguity.',
    placeholder: 'e.g., 100 daily active users, < 2s load time, zero critical bugs',
    type: 'text',
    required: false,
    complexityTrigger: 'deep',
  },
];
