// [SCOPE] Blueprint writer — writeBlueprintMd function for writing blueprint.md file
// Called by blueprintService. No interview or health calculation logic here.

import * as fs from 'fs';
import * as path from 'path';
import type { Blueprint } from '../../../types/index.js';

// [LIVING BLUEPRINT] Render the user prompts that built/changed this project — read from the revision ledger
// (blueprint_revisions.jsonl, a sibling of blueprint.md). Oldest-to-newest, last 20, so the blueprint shows WHAT
// the user actually asked for over time alongside WHAT the project does. Returns '' if there is no ledger.
function _requestHistorySection(blueprintPath: string): string {
  try {
    const ledger = path.join(path.dirname(blueprintPath), 'blueprint_revisions.jsonl');
    const revs = fs.readFileSync(ledger, 'utf-8').split('\n').filter(l => l.trim())
      .map(l => { try { return JSON.parse(l); } catch { return null; } }).filter(Boolean) as any[];
    if (!revs.length) { return ''; }
    const items = revs.slice(-20).map(r => {
      const req = String(r.request || '').replace(/\s+/g, ' ').trim().slice(0, 240) || '(no prompt recorded)';
      return `- **${r.kind}** (rev ${r.rev}): "${req}"`;
    }).join('\n');
    return `
## REQUEST HISTORY
<!-- The user prompts that built and changed this project, oldest-to-newest. Auto-maintained from
     blueprint_revisions.jsonl — the record of WHAT was asked for, alongside the MECHANICS (what it does). -->
${items}
`;
  } catch { return ''; }
}

export function writeBlueprintMd(bp: Blueprint, blueprintPath: string, projectName: string): void {
  const status = bp.locked ? '🔒 LOCKED' : '🔶 DRAFT';
  const content = `# Blueprint — ${projectName}

**Status:** ${status}
${bp.lockedAt ? `**Locked at:** ${bp.lockedAt}` : ''}

---

## WHO
${bp.who || '❓ Not answered'}

## WHAT
${bp.what || '❓ Not answered'}

## WHERE
${bp.where || '❓ Not answered'}

## WHEN
${bp.when || '❓ Not answered'}

## WHY
${bp.why || '❓ Not answered'}
${bp.mechanics ? `
## MECHANICS
<!-- Behavioral contract (HEAD). What the project SHOULD do, observable only. The fix-Supervisor diffs this
     against the code to diagnose issues. See REDIVIVUS_LIVING_BLUEPRINT.md. -->
${bp.mechanics}
` : ''}
---

## Health
- ✅ Confirmed: ${bp.health.confirmed}
- 🔶 Assumed: ${bp.health.assumed}
- ❓ Unknown: ${bp.health.unknown}
- **Confidence:** ${bp.health.confidence.toUpperCase()}
${_requestHistorySection(blueprintPath)}
---

*Generated by Redivivus v${bp.version}*
`;
  // [WARN] Direct file system write, potential for path/permission errors.
  fs.writeFileSync(blueprintPath, content);
}

// [SCOPE] Syncs the internal .redivivus/blueprint.md with the current config blueprint
// Call this everywhere saveConfig is called with updated blueprint data
export function syncBlueprintMd(redivivus: any, config: any): void {
  if (!config || !config.blueprint || !redivivus.blueprintPath) {return;}
  writeBlueprintMd(config.blueprint, redivivus.blueprintPath, config.projectName || 'Unknown');
}
