// [SCOPE] PWA templates (Phase 0) — pure string builders for the files that turn a web bundle into an installable
// PWA: manifest.json, a precache service worker, a generated title-tile icon, the <head>/<body> injections, and the
// "Made with Redivivus" badge. No I/O, no deps — unit-testable. See docs/REDIVIVUS_ADD_TO_PHONE.md.

function escXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export interface ManifestOpts {
  name: string;
  shortName?: string;
  themeColor: string;
  backgroundColor: string;
  orientation: 'any' | 'portrait' | 'landscape';
}

// Web App Manifest. Icons reference the generated SVG (resolution-independent; PNG rasterization is Phase 3 polish).
export function manifestJson(o: ManifestOpts): string {
  return JSON.stringify({
    name: o.name,
    short_name: (o.shortName || o.name).slice(0, 12),
    start_url: '.',
    scope: '.',
    display: 'standalone',
    orientation: o.orientation,
    theme_color: o.themeColor,
    background_color: o.backgroundColor,
    icons: [
      { src: 'icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any maskable' },
      { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any maskable' },
      { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' },
    ],
  }, null, 2);
}

// Precache service worker: cache the whole bundle on install (so the app runs offline AND survives the host's
// ephemeral expiry — see the doc's "install window != run lifetime"). Cache-first at runtime.
export function serviceWorkerJs(files: string[], version: string): string {
  const assets = JSON.stringify(['./', ...files.filter(f => f !== 'sw.js')]);
  return `// Auto-generated by Redivivus — precache PWA service worker.
const CACHE = 'rdv-${version}';
const ASSETS = ${assets};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  e.respondWith(caches.match(e.request).then((hit) => hit || fetch(e.request).catch(() => caches.match('./'))));
});
`;
}

// A clean title-tile icon: up to two initials on a theme-colored gradient. SVG scales to any size (192/512/…).
export function iconSvg(title: string, themeColor: string, backgroundColor: string): string {
  const words = title.split(/[\s\-_]+/).filter(Boolean);
  const initials = (words.length >= 2 ? words[0][0] + words[1][0] : (title.replace(/[^a-z0-9]/gi, '').slice(0, 2)))
    .toUpperCase() || 'AP';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
  <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="${escXml(themeColor)}"/>
    <stop offset="1" stop-color="${escXml(backgroundColor)}"/>
  </linearGradient></defs>
  <rect width="512" height="512" rx="96" fill="url(#g)"/>
  <text x="256" y="276" font-family="system-ui,-apple-system,sans-serif" font-size="240" font-weight="700"
        fill="#ffffff" text-anchor="middle" dominant-baseline="middle">${escXml(initials)}</text>
</svg>
`;
}

// Small, unobtrusive "Made with Redivivus" badge (free tier). Tamper-resistant enforcement happens server-side at
// publish; this is the default markup. Corner chip, low profile, never covers controls.
export function madeWithBadge(): string {
  return `
  <a id="rdv-badge" href="https://redivivus.dev" target="_blank" rel="noopener"
     style="position:fixed;right:8px;bottom:8px;z-index:2147483647;font:600 11px system-ui,sans-serif;
            color:#fff;background:rgba(0,0,0,.55);padding:3px 8px;border-radius:10px;text-decoration:none;
            opacity:.75;pointer-events:auto">Made with Redivivus</a>`;
}

// In-page install prompt — novices won't know the browser's hidden "Add to Home Screen" menu. Android/desktop
// Chrome: capture beforeinstallprompt and show a real Install button. iOS Safari (no auto-prompt): show the
// Share -> Add to Home Screen instruction. Hidden once installed (display-mode: standalone) or dismissed.
function installBanner(): string {
  return `
  <div id="rdv-install" style="display:none;position:fixed;left:0;right:0;top:0;z-index:2147483646;align-items:center;gap:10px;background:#0ea5e9;color:#fff;font:600 14px system-ui,sans-serif;padding:11px 12px;box-shadow:0 2px 14px rgba(0,0,0,.35)">
    <span id="rdv-install-text" style="flex:1">Install this app on your device</span>
    <button id="rdv-install-btn" style="background:#fff;color:#0369a1;border:0;border-radius:8px;padding:8px 16px;font:700 14px system-ui,sans-serif">Install</button>
    <button id="rdv-install-x" aria-label="Dismiss" style="background:transparent;color:#fff;border:0;font-size:22px;line-height:1;padding:0 6px">&times;</button>
  </div>
  <script>(function(){
    var bar=document.getElementById('rdv-install'),btn=document.getElementById('rdv-install-btn'),
        txt=document.getElementById('rdv-install-text'),x=document.getElementById('rdv-install-x'),dp=null;
    function standalone(){return window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;}
    if(standalone())return;
    x.onclick=function(){bar.style.display='none';};
    window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();dp=e;btn.style.display='';bar.style.display='flex';});
    btn.onclick=function(){if(dp){dp.prompt();dp.userChoice.then(function(){bar.style.display='none';dp=null;});}};
    window.addEventListener('appinstalled',function(){bar.style.display='none';});
    var ua=navigator.userAgent||'';
    if(/iphone|ipad|ipod/i.test(ua)&&/safari/i.test(ua)&&!/crios|fxios|edgios|android/i.test(ua)){
      txt.innerHTML='To install: tap <b>Share</b> &#8593; then <b>Add to Home Screen</b>';btn.style.display='none';bar.style.display='flex';}
  })();</script>`;
}

// Tap-to-start bridge — phones have no Enter key, but many games gate start/restart on Enter or Space. Fire those
// keys on a tap in empty (non-control) areas, so "Press ENTER to start" works by tapping. Best-effort: ignores taps
// on the game's own buttons/inputs so it never double-handles real controls. (Long-term, builds should be touch-native.)
function tapToStartBridge(): string {
  return `
  <script>(function(){
    function fire(t,key,code,kc){var e;try{e=new KeyboardEvent(t,{key:key,code:code,bubbles:true,cancelable:true});}catch(_){e=document.createEvent('Event');e.initEvent(t,true,true);e.key=key;}
      try{Object.defineProperty(e,'keyCode',{get:function(){return kc;}});Object.defineProperty(e,'which',{get:function(){return kc;}});}catch(_){}
      document.dispatchEvent(e);window.dispatchEvent(e);}
    function start(){fire('keydown','Enter','Enter',13);fire('keyup','Enter','Enter',13);fire('keydown',' ','Space',32);fire('keyup',' ','Space',32);}
    document.addEventListener('pointerup',function(ev){
      if(ev.pointerType&&ev.pointerType!=='touch')return; /* only touch devices — mouse/pen users have real keys */
      var t=ev.target;if(t&&t.closest&&t.closest('button,a,input,select,textarea,[role=button]'))return;start();},true);
  })();</script>`;
}

// Inject the PWA wiring into the entry HTML: manifest, theme-color, Apple meta, the SW registration, and the badge.
export function injectPwaIntoHtml(html: string, o: { title: string; themeColor: string; includeBadge: boolean }): string {
  const head = `
  <link rel="manifest" href="manifest.json">
  <meta name="theme-color" content="${escXml(o.themeColor)}">
  <link rel="apple-touch-icon" href="icon-192.png">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="apple-mobile-web-app-title" content="${escXml(o.title)}">`;
  const reg = `
  <script>
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('sw.js').catch(function () {});
    }
  </script>`;
  const tail = reg + installBanner() + tapToStartBridge() + (o.includeBadge ? madeWithBadge() : '');
  html = html.includes('</head>') ? html.replace('</head>', `${head}\n</head>`) : head + '\n' + html;
  html = html.includes('</body>') ? html.replace('</body>', `${tail}\n</body>`) : html + tail;
  return html;
}
