// [SCOPE] PWA templates (Phase 0) — pure string builders for the files that turn a web bundle into an installable
// PWA: manifest.json, a precache service worker, a generated title-tile icon, the <head>/<body> injections, and the
// "Made with Redivivus" badge. No I/O, no deps — unit-testable. See docs/REDIVIVUS_ADD_TO_PHONE.md.

function escXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export interface ManifestOpts {
  name: string;
  shortName?: string;
  themeColor: string;
  backgroundColor: string;
  orientation: 'any' | 'portrait' | 'landscape';
}

// Web App Manifest. Icons reference the generated SVG (resolution-independent; PNG rasterization is Phase 3 polish).
export function manifestJson(o: ManifestOpts): string {
  return JSON.stringify({
    name: o.name,
    short_name: (o.shortName || o.name).slice(0, 12),
    start_url: '.',
    scope: '.',
    display: 'standalone',
    orientation: o.orientation,
    theme_color: o.themeColor,
    background_color: o.backgroundColor,
    icons: [
      { src: 'icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any maskable' },
      { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any maskable' },
      { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' },
    ],
  }, null, 2);
}

// Precache service worker: cache the whole bundle on install (so the app runs offline AND survives the host's
// ephemeral expiry — see the doc's "install window != run lifetime"). Cache-first at runtime.
export function serviceWorkerJs(files: string[], version: string): string {
  const assets = JSON.stringify(['./', ...files.filter(f => f !== 'sw.js')]);
  return `// Auto-generated by Redivivus — precache PWA service worker.
const CACHE = 'rdv-${version}';
const ASSETS = ${assets};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  e.respondWith(caches.match(e.request).then((hit) => hit || fetch(e.request).catch(() => caches.match('./'))));
});
`;
}

// A clean title-tile icon: up to two initials on a theme-colored gradient. SVG scales to any size (192/512/…).
export function iconSvg(title: string, themeColor: string, backgroundColor: string): string {
  const words = title.split(/[\s\-_]+/).filter(Boolean);
  const initials = (words.length >= 2 ? words[0][0] + words[1][0] : (title.replace(/[^a-z0-9]/gi, '').slice(0, 2)))
    .toUpperCase() || 'AP';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
  <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="${escXml(themeColor)}"/>
    <stop offset="1" stop-color="${escXml(backgroundColor)}"/>
  </linearGradient></defs>
  <rect width="512" height="512" rx="96" fill="url(#g)"/>
  <text x="256" y="276" font-family="system-ui,-apple-system,sans-serif" font-size="240" font-weight="700"
        fill="#ffffff" text-anchor="middle" dominant-baseline="middle">${escXml(initials)}</text>
</svg>
`;
}

// Small, unobtrusive "Made with Redivivus" badge (free tier). Tamper-resistant enforcement happens server-side at
// publish; this is the default markup. Corner chip, low profile, never covers controls.
export function madeWithBadge(): string {
  return `
  <a id="rdv-badge" href="https://redivivus.dev" target="_blank" rel="noopener"
     style="position:fixed;right:8px;bottom:8px;z-index:2147483647;font:600 11px system-ui,sans-serif;
            color:#fff;background:rgba(0,0,0,.55);padding:3px 8px;border-radius:10px;text-decoration:none;
            opacity:.75;pointer-events:auto">Made with Redivivus</a>`;
}

// Inject the PWA wiring into the entry HTML: manifest, theme-color, Apple meta, the SW registration, and the badge.
export function injectPwaIntoHtml(html: string, o: { title: string; themeColor: string; includeBadge: boolean }): string {
  const head = `
  <link rel="manifest" href="manifest.json">
  <meta name="theme-color" content="${escXml(o.themeColor)}">
  <link rel="apple-touch-icon" href="icon-192.png">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="apple-mobile-web-app-title" content="${escXml(o.title)}">`;
  const reg = `
  <script>
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('sw.js').catch(function () {});
    }
  </script>`;
  const tail = reg + (o.includeBadge ? madeWithBadge() : '');
  html = html.includes('</head>') ? html.replace('</head>', `${head}\n</head>`) : head + '\n' + html;
  html = html.includes('</body>') ? html.replace('</body>', `${tail}\n</body>`) : html + tail;
  return html;
}
